name: Flutter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Flutter SDK (ensure correct version for Dart 3.x)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'  # Make sure this is the correct Flutter version

      # Clear the Flutter cache to ensure the right version of Dart is being used
      - name: Clean Flutter cache
        run: flutter clean

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Analyze project source
      - name: Analyze project source
        run: flutter analyze

      # Run tests (for Flutter projects, use flutter test)
      - name: Run tests
        run: flutter test
